# Generated by Django 3.1.2 on 2020-10-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50, verbose_name='Время')),
                ('predmet', models.CharField(max_length=50, verbose_name='Предмет')),
                ('title', models.CharField(max_length=50, verbose_name='Преподаватель')),
                ('kab', models.CharField(max_length=50, verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'расписание',
                'verbose_name_plural': 'расписание',
            },
        ),
    ]
