# Generated by Django 3.1.2 on 2020-10-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50, verbose_name='День')),
                ('time', models.CharField(max_length=50, verbose_name='Время')),
                ('predmet', models.CharField(max_length=50, verbose_name='Предмет')),
                ('title', models.CharField(max_length=50, verbose_name='Преподаватель')),
                ('kab', models.CharField(max_length=50, verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
            },
        ),
    ]
